# Builder Image. 
FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o upload-service

# Runtime Image without golang. Copies the builder's output binaries
FROM alpine:3.22
WORKDIR /app

COPY --from=builder /app/upload-service .

RUN addgroup -S app && \
    adduser -S app -G app
USER app

EXPOSE 8080
ENTRYPOINT ["./upload-service"]
