# Builder Image. 
FROM golang:alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o upload-service

# Runtime Image without golang. Copies the builder's output binaries
FROM alpine:3
WORKDIR /app

COPY --from=builder /app/upload-service .

EXPOSE 8080

ENTRYPOINT ["./upload-service"]
