FROM python:3.12-alpine

# No byte code inside containers and don't buffer stdout.
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY wildcam .

ENTRYPOINT ["python", "-m", "wildcam"]
